# Generated by Django 6.1 on 2026-08-21 01:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='タイトル')),
                ('category', models.CharField(choices=[('イベント', 'イベント'), ('レジャー・グルメ', 'レジャー・グルメ'), ('自然・癒し', '自然・癒し'), ('その他', 'その他')], max_length=20, verbose_name='カテゴリ')),
                ('due_date', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2026, 8, 31), message='実行したい日は2026年8月31日以前にしてください。')], verbose_name='実行したい日')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
    ]
