# Generated by Django 5.2.17 on 2026-08-21 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=280)),
                ('occurred_at', models.DateTimeField()),
                ('entry_type', models.CharField(choices=[('moment', 'moment'), ('reflection', 'reflection')], default='moment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moment_logs', to='core.category')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_logs', to='core.room')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moment_logs', to='core.task')),
            ],
        ),
    ]
