# Generated by Django 5.2.17 on 2026-08-21 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_momentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='moment_photos/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moment_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.momentlog')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
