# Generated by Django 5.2.17 on 2026-08-27 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='room_ends_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('reflection_deadline_at__isnull', True), ('reflection_deadline_at__gte', models.F('ends_at')), _connector='OR'), name='room_reflection_deadline_after_end'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('is_completed', True)), models.Q(('completed_at__isnull', True), ('is_completed', False)), _connector='OR'), name='task_completion_timestamp_matches_status'),
        ),
    ]
