# Generated by Django 5.2.17 on 2026-08-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_room_room_ends_after_starts_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='momentlog',
            constraint=models.CheckConstraint(condition=models.Q(('entry_type__in', ['moment', 'reflection'])), name='moment_log_entry_type_is_valid'),
        ),
    ]
