# Generated by Django 5.2.17 on 2026-08-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_postgresql_integrity_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='captured_at',
            field=models.DateTimeField(blank=True, help_text='EXIFまたは利用者が指定した撮影日時', null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='captured_at_source',
            field=models.CharField(choices=[('exif', 'exif'), ('manual', 'manual'), ('unknown', 'unknown')], default='unknown', max_length=10),
        ),
    ]
